# Generated by Django 6.0.2 on 2026-03-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_metalrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='making_charges',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Making charges (Flat per gram or absolute)', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='metal_type',
            field=models.CharField(choices=[('GOLD_24K', 'Gold 24K'), ('GOLD_22K', 'Gold 22K'), ('SILVER', 'Silver'), ('FIXED', 'Fixed Price (No auto-calc)')], default='FIXED', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Weight in grams', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Manual price override (optional). Set to 0 to use auto-calculation.', max_digits=10),
        ),
    ]
